# Generated by Django 6.0.7 on 2026-08-04 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urbanizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('urbanizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manzanas', to='ubicaciones.urbanizacion')),
            ],
            options={
                'unique_together': {('numero', 'urbanizacion')},
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('manzana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villas', to='ubicaciones.manzana')),
            ],
            options={
                'unique_together': {('numero', 'manzana')},
            },
        ),
    ]
